version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "8070:80"
    volumes:
      - ./:/var/www/html
      - ./composer.json:/var/www/html/composer.json
    environment:
      - DB_HOST=db
      - DB_NAME=utmdb
      - DB_USER=utmuser
      - DB_PASS=utmpass
      # config core.php
      - SECURITY_SALT=f8b7a03e8d2a4a2195d6c72c1b9ef9b4b1c3e8ad7a2f4c6d9e0a1b2c3d4e5f60
      - SECURITY_CIPHER_SEED=93847502938475029384750293847502938475
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: utmdb
      MYSQL_USER: utmuser
      MYSQL_PASSWORD: utmpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3305:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
