CREATE TABLE IF NOT EXISTS utm_data (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	source   VARCHAR(190) NOT NULL,
	medium   VARCHAR(190) NOT NULL,
	campaign VARCHAR(190) NOT NULL,
	content  VARCHAR(190) NULL,
	term     VARCHAR(190) NULL,
	KEY idx_source (source),
	KEY idx_source_medium (source, medium),
	KEY idx_source_medium_campaign (source, medium, campaign),
	KEY idx_source_medium_campaign_content (source, medium, campaign, content)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


INSERT INTO utm_data (source, medium, campaign, content, term)
VALUES
	('google', 'cpc', 'summer', 'banner', 'video'),
	('google', 'cpc', 'winter', 'delta', null),
	('google', 'cpc', 'summer', null, null),
	('source1', 'medium1', 'summer', 'delta', 'video'),
	('source1', 'medium2', 'summer', 'banner', 'video'),
	('source1', 'medium3', 'summer', 'banner', null),
	('source1', 'medium1', 'spring', 'delta', 'video'),
	('source1', 'medium2', 'spring', 'banner', 'video'),
	('source2', 'medium1', 'summer', 'delta', 'video'),
	('source2', 'medium1', 'summer', null, null),
	('source2', 'medium3', 'spring', 'delta', 'video'),
	('source3', 'cpc', 'summer', 'banner', 'video'),
	('source4', 'medium1', 'spring', 'banner', 'video'),
	('source5', 'cpc', 'winter', 'banner', 'video'),
	('source6', 'medium1', 'spring', 'delta', 'video'),
	('source7', 'medium1', 'spring', 'delta', 'video'),
	('source8', 'medium1', 'spring', 'delta', 'video'),
	('source9', 'medium1', 'spring', 'delta', 'video'),
	('source10', 'medium1', 'spring', 'delta', 'video'),
	('source11', 'medium1', 'spring', 'delta', 'video'),
	('source12', 'medium1', 'spring', 'delta', 'video'),
	('source13', 'medium1', 'spring', 'delta', 'video'),
	('source14', 'medium1', 'spring', 'delta', 'video'),
	('source15', 'medium1', 'spring', 'delta', 'video'),
	('source16', 'medium1', 'spring', 'delta', 'video'),
	('source17', 'medium1', 'spring', 'delta', 'video'),
	('source18', 'medium1', 'spring', 'delta', 'video'),
	('source19', 'medium1', 'spring', 'delta', 'video'),
	('source20', 'medium1', 'spring', 'delta', 'video'),
	('source21', 'medium1', 'spring', 'delta', 'video'),
	('source22', 'medium1', 'spring', 'delta', 'video'),
	('source23', 'medium1', 'spring', 'delta', 'video'),
	('source24', 'medium1', 'spring', 'delta', 'video'),
	('source25', 'medium1', 'spring', 'delta', 'video'),
	('source26', 'medium1', 'spring', 'delta', 'video'),
	('source27', 'medium1', 'spring', 'delta', 'video'),
	('source28', 'medium1', 'spring', 'delta', 'video'),
	('source29', 'medium1', 'spring', 'delta', 'video'),
	('source30', 'medium1', 'spring', 'delta', 'video')
	;
